json.extract! store, :categories,
                     :coordinates,
                     :display_phone,
                     :hours,
                     :id,
                     :image_url,
                     :is_closed,
                     :location,
                     :name,
                     :phone,
                     :photos,
                     :price,
                     :rating,
